# After changing this file, check it on:
#   http://lint.travis-ci.org/
#
language: python

python:
  - "3.6"

os:
  - linux
#  - windows For some reason python is not supported on Travis CI now?!

install:
  - pip install -r requirements.txt

script:
  - pytest tests.py

notificiations:
  email: false
