# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyFORCGUIBase.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1211, 871)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.d_jobs = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_jobs.sizePolicy().hasHeightForWidth())
        self.d_jobs.setSizePolicy(sizePolicy)
        self.d_jobs.setMinimumSize(QtCore.QSize(100, 0))
        self.d_jobs.setMaximumSize(QtCore.QSize(100, 16777215))
        self.d_jobs.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.d_jobs.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.d_jobs.setObjectName("d_jobs")
        self.verticalLayout.addWidget(self.d_jobs)
        self.b_undo = QtWidgets.QPushButton(self.centralwidget)
        self.b_undo.setObjectName("b_undo")
        self.verticalLayout.addWidget(self.b_undo)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.t_tabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_tabs.sizePolicy().hasHeightForWidth())
        self.t_tabs.setSizePolicy(sizePolicy)
        self.t_tabs.setMaximumSize(QtCore.QSize(240, 16777215))
        self.t_tabs.setDocumentMode(True)
        self.t_tabs.setTabsClosable(False)
        self.t_tabs.setTabBarAutoHide(False)
        self.t_tabs.setObjectName("t_tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem = QtWidgets.QSpacerItem(20, 397, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem, 3, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 2)
        self.f_auto_slope = QtWidgets.QCheckBox(self.groupBox)
        self.f_auto_slope.setChecked(True)
        self.f_auto_slope.setObjectName("f_auto_slope")
        self.gridLayout.addWidget(self.f_auto_slope, 1, 0, 1, 1)
        self.f_slope_h_sat = QtWidgets.QLineEdit(self.groupBox)
        self.f_slope_h_sat.setObjectName("f_slope_h_sat")
        self.gridLayout.addWidget(self.f_slope_h_sat, 0, 2, 1, 1)
        self.f_slope = QtWidgets.QLineEdit(self.groupBox)
        self.f_slope.setEnabled(False)
        self.f_slope.setObjectName("f_slope")
        self.gridLayout.addWidget(self.f_slope, 1, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.f_drift = QtWidgets.QCheckBox(self.groupBox_9)
        self.f_drift.setChecked(True)
        self.f_drift.setObjectName("f_drift")
        self.gridLayout_7.addWidget(self.f_drift, 0, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.groupBox_9)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_9)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_9)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_9)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 4, 0, 1, 1)
        self.f_step_auto = QtWidgets.QCheckBox(self.groupBox_9)
        self.f_step_auto.setChecked(True)
        self.f_step_auto.setObjectName("f_step_auto")
        self.gridLayout_7.addWidget(self.f_step_auto, 4, 1, 1, 2)
        self.f_step_manual = QtWidgets.QLineEdit(self.groupBox_9)
        self.f_step_manual.setEnabled(False)
        self.f_step_manual.setObjectName("f_step_manual")
        self.gridLayout_7.addWidget(self.f_step_manual, 4, 3, 1, 1)
        self.f_dataset_interpolation_type = QtWidgets.QComboBox(self.groupBox_9)
        self.f_dataset_interpolation_type.setObjectName("f_dataset_interpolation_type")
        self.f_dataset_interpolation_type.addItem("")
        self.f_dataset_interpolation_type.addItem("")
        self.f_dataset_interpolation_type.addItem("")
        self.gridLayout_7.addWidget(self.f_dataset_interpolation_type, 3, 3, 1, 1)
        self.f_drift_radius = QtWidgets.QSpinBox(self.groupBox_9)
        self.f_drift_radius.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f_drift_radius.setMaximum(999999999)
        self.f_drift_radius.setProperty("value", 4)
        self.f_drift_radius.setObjectName("f_drift_radius")
        self.gridLayout_7.addWidget(self.f_drift_radius, 2, 3, 1, 1)
        self.f_drift_density = QtWidgets.QSpinBox(self.groupBox_9)
        self.f_drift_density.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f_drift_density.setMaximum(999999999)
        self.f_drift_density.setProperty("value", 3)
        self.f_drift_density.setObjectName("f_drift_density")
        self.gridLayout_7.addWidget(self.f_drift_density, 1, 3, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_9, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.f_smoothing_factor = QtWidgets.QSpinBox(self.groupBox_2)
        self.f_smoothing_factor.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f_smoothing_factor.setAccelerated(False)
        self.f_smoothing_factor.setMinimum(0)
        self.f_smoothing_factor.setMaximum(999999999)
        self.f_smoothing_factor.setProperty("value", 3)
        self.f_smoothing_factor.setObjectName("f_smoothing_factor")
        self.gridLayout_2.addWidget(self.f_smoothing_factor, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.f_extension_type = QtWidgets.QComboBox(self.groupBox_2)
        self.f_extension_type.setObjectName("f_extension_type")
        self.f_extension_type.addItem("")
        self.f_extension_type.addItem("")
        self.f_extension_type.addItem("")
        self.gridLayout_2.addWidget(self.f_extension_type, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setEnabled(False)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.f_extension_n_fit_points = QtWidgets.QSpinBox(self.groupBox_2)
        self.f_extension_n_fit_points.setEnabled(False)
        self.f_extension_n_fit_points.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f_extension_n_fit_points.setMinimum(10)
        self.f_extension_n_fit_points.setMaximum(999999999)
        self.f_extension_n_fit_points.setObjectName("f_extension_n_fit_points")
        self.gridLayout_2.addWidget(self.f_extension_n_fit_points, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.t_tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_11.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_11.setFlat(True)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_14 = QtWidgets.QLabel(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 1)
        self.f_2d_mask = QtWidgets.QComboBox(self.groupBox_11)
        self.f_2d_mask.setMaximumSize(QtCore.QSize(65, 16777215))
        self.f_2d_mask.setObjectName("f_2d_mask")
        self.f_2d_mask.addItem("")
        self.f_2d_mask.addItem("")
        self.gridLayout_5.addWidget(self.f_2d_mask, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 1, 0, 1, 1)
        self.f_2d_cmap = QtWidgets.QLineEdit(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_2d_cmap.sizePolicy().hasHeightForWidth())
        self.f_2d_cmap.setSizePolicy(sizePolicy)
        self.f_2d_cmap.setMaximumSize(QtCore.QSize(65, 16777215))
        self.f_2d_cmap.setObjectName("f_2d_cmap")
        self.gridLayout_5.addWidget(self.f_2d_cmap, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox_11)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.f_hhr = QtWidgets.QRadioButton(self.groupBox_11)
        self.f_hhr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.f_hhr.setChecked(True)
        self.f_hhr.setObjectName("f_hhr")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.f_hhr)
        self.verticalLayout_7.addWidget(self.f_hhr)
        self.f_hchb = QtWidgets.QRadioButton(self.groupBox_11)
        self.f_hchb.setObjectName("f_hchb")
        self.buttonGroup.addButton(self.f_hchb)
        self.verticalLayout_7.addWidget(self.f_hchb)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        self.verticalLayout_8.addWidget(self.groupBox_11)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_10.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_10.setFlat(True)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_15 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_9.addWidget(self.label_15, 0, 0, 1, 1)
        self.f_paths_mask = QtWidgets.QComboBox(self.groupBox_10)
        self.f_paths_mask.setMaximumSize(QtCore.QSize(65, 16777215))
        self.f_paths_mask.setObjectName("f_paths_mask")
        self.f_paths_mask.addItem("")
        self.f_paths_mask.addItem("")
        self.f_paths_mask.addItem("")
        self.gridLayout_9.addWidget(self.f_paths_mask, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_9.addWidget(self.label_13, 1, 0, 1, 1)
        self.f_paths_cmap = QtWidgets.QComboBox(self.groupBox_10)
        self.f_paths_cmap.setMaximumSize(QtCore.QSize(65, 16777215))
        self.f_paths_cmap.setObjectName("f_paths_cmap")
        self.f_paths_cmap.addItem("")
        self.gridLayout_9.addWidget(self.f_paths_cmap, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 2, 0, 1, 1)
        self.f_paths_points = QtWidgets.QComboBox(self.groupBox_10)
        self.f_paths_points.setMaximumSize(QtCore.QSize(65, 16777215))
        self.f_paths_points.setObjectName("f_paths_points")
        self.f_paths_points.addItem("")
        self.f_paths_points.addItem("")
        self.f_paths_points.addItem("")
        self.gridLayout_9.addWidget(self.f_paths_points, 2, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_10)
        spacerItem2 = QtWidgets.QSpacerItem(20, 585, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.t_tabs.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(20, 659, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3, 1, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.b_export_vtk = QtWidgets.QPushButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_export_vtk.setFont(font)
        self.b_export_vtk.setObjectName("b_export_vtk")
        self.verticalLayout_6.addWidget(self.b_export_vtk)
        self.b_export_csv = QtWidgets.QPushButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_export_csv.setFont(font)
        self.b_export_csv.setObjectName("b_export_csv")
        self.verticalLayout_6.addWidget(self.b_export_csv)
        self.b_export_pmc = QtWidgets.QPushButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_export_pmc.setFont(font)
        self.b_export_pmc.setObjectName("b_export_pmc")
        self.verticalLayout_6.addWidget(self.b_export_pmc)
        self.gridLayout_6.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.t_tabs.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.t_tabs)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.b_import = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_import.setFont(font)
        self.b_import.setObjectName("b_import")
        self.verticalLayout_2.addWidget(self.b_import)
        self.b_slope = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_slope.setFont(font)
        self.b_slope.setObjectName("b_slope")
        self.verticalLayout_2.addWidget(self.b_slope)
        self.b_normalize = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_normalize.setFont(font)
        self.b_normalize.setObjectName("b_normalize")
        self.verticalLayout_2.addWidget(self.b_normalize)
        self.b_gauss = QtWidgets.QPushButton(self.groupBox_3)
        self.b_gauss.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_gauss.setFont(font)
        self.b_gauss.setObjectName("b_gauss")
        self.verticalLayout_2.addWidget(self.b_gauss)
        self.b_forc = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_forc.setFont(font)
        self.b_forc.setObjectName("b_forc")
        self.verticalLayout_2.addWidget(self.b_forc)
        self.verticalLayout_13.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.b_heat_moment = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_heat_moment.setFont(font)
        self.b_heat_moment.setObjectName("b_heat_moment")
        self.verticalLayout_4.addWidget(self.b_heat_moment)
        self.b_heat_rho = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_heat_rho.setFont(font)
        self.b_heat_rho.setObjectName("b_heat_rho")
        self.verticalLayout_4.addWidget(self.b_heat_rho)
        self.b_heat_rho_uncertainty = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_heat_rho_uncertainty.setFont(font)
        self.b_heat_rho_uncertainty.setObjectName("b_heat_rho_uncertainty")
        self.verticalLayout_4.addWidget(self.b_heat_rho_uncertainty)
        self.b_heat_temperature = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_heat_temperature.setFont(font)
        self.b_heat_temperature.setObjectName("b_heat_temperature")
        self.verticalLayout_4.addWidget(self.b_heat_temperature)
        self.gridLayout_3.addWidget(self.groupBox_5, 5, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_12.setFlat(True)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.b_level_moment = QtWidgets.QPushButton(self.groupBox_12)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_level_moment.setFont(font)
        self.b_level_moment.setObjectName("b_level_moment")
        self.verticalLayout_9.addWidget(self.b_level_moment)
        self.b_level_rho = QtWidgets.QPushButton(self.groupBox_12)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_level_rho.setFont(font)
        self.b_level_rho.setObjectName("b_level_rho")
        self.verticalLayout_9.addWidget(self.b_level_rho)
        self.b_level_rho_uncertainty = QtWidgets.QPushButton(self.groupBox_12)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_level_rho_uncertainty.setFont(font)
        self.b_level_rho_uncertainty.setObjectName("b_level_rho_uncertainty")
        self.verticalLayout_9.addWidget(self.b_level_rho_uncertainty)
        self.b_level_temperature = QtWidgets.QPushButton(self.groupBox_12)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_level_temperature.setFont(font)
        self.b_level_temperature.setObjectName("b_level_temperature")
        self.verticalLayout_9.addWidget(self.b_level_temperature)
        self.gridLayout_3.addWidget(self.groupBox_12, 5, 2, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.b_contour_moment = QtWidgets.QPushButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_contour_moment.setFont(font)
        self.b_contour_moment.setObjectName("b_contour_moment")
        self.verticalLayout_3.addWidget(self.b_contour_moment)
        self.b_contour_rho = QtWidgets.QPushButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_contour_rho.setFont(font)
        self.b_contour_rho.setObjectName("b_contour_rho")
        self.verticalLayout_3.addWidget(self.b_contour_rho)
        self.b_contour_rho_uncertainty = QtWidgets.QPushButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_contour_rho_uncertainty.setFont(font)
        self.b_contour_rho_uncertainty.setObjectName("b_contour_rho_uncertainty")
        self.verticalLayout_3.addWidget(self.b_contour_rho_uncertainty)
        self.b_contour_temperature = QtWidgets.QPushButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_contour_temperature.setFont(font)
        self.b_contour_temperature.setObjectName("b_contour_temperature")
        self.verticalLayout_3.addWidget(self.b_contour_temperature)
        self.gridLayout_3.addWidget(self.groupBox_6, 5, 1, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.b_map_curves_moment = QtWidgets.QPushButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_map_curves_moment.setFont(font)
        self.b_map_curves_moment.setObjectName("b_map_curves_moment")
        self.verticalLayout_5.addWidget(self.b_map_curves_moment)
        self.b_map_curves_rho = QtWidgets.QPushButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_map_curves_rho.setFont(font)
        self.b_map_curves_rho.setObjectName("b_map_curves_rho")
        self.verticalLayout_5.addWidget(self.b_map_curves_rho)
        self.b_map_curves_rho_uncertainty = QtWidgets.QPushButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_map_curves_rho_uncertainty.setFont(font)
        self.b_map_curves_rho_uncertainty.setObjectName("b_map_curves_rho_uncertainty")
        self.verticalLayout_5.addWidget(self.b_map_curves_rho_uncertainty)
        self.b_map_curves_temperature = QtWidgets.QPushButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_map_curves_temperature.setFont(font)
        self.b_map_curves_temperature.setObjectName("b_map_curves_temperature")
        self.verticalLayout_5.addWidget(self.b_map_curves_temperature)
        self.gridLayout_3.addWidget(self.groupBox_7, 6, 0, 1, 3)
        self.b_hc_axis = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_hc_axis.setFont(font)
        self.b_hc_axis.setObjectName("b_hc_axis")
        self.gridLayout_3.addWidget(self.b_hc_axis, 2, 1, 1, 2)
        self.b_paths = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_paths.setFont(font)
        self.b_paths.setObjectName("b_paths")
        self.gridLayout_3.addWidget(self.b_paths, 0, 0, 1, 1)
        self.b_h_axis = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_h_axis.setFont(font)
        self.b_h_axis.setObjectName("b_h_axis")
        self.gridLayout_3.addWidget(self.b_h_axis, 0, 1, 1, 2)
        self.b_data_points = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_data_points.setFont(font)
        self.b_data_points.setObjectName("b_data_points")
        self.gridLayout_3.addWidget(self.b_data_points, 4, 0, 1, 1)
        self.b_hb_axis = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_hb_axis.setFont(font)
        self.b_hb_axis.setObjectName("b_hb_axis")
        self.gridLayout_3.addWidget(self.b_hb_axis, 4, 1, 1, 2)
        self.b_hr_axis = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_hr_axis.setFont(font)
        self.b_hr_axis.setObjectName("b_hr_axis")
        self.gridLayout_3.addWidget(self.b_hr_axis, 1, 1, 1, 2)
        self.b_major_loop = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_major_loop.setFont(font)
        self.b_major_loop.setObjectName("b_major_loop")
        self.gridLayout_3.addWidget(self.b_major_loop, 1, 0, 1, 1)
        self.verticalLayout_13.addWidget(self.groupBox_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.verticalLayout_13)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.t_paths = QtWidgets.QWidget()
        self.t_paths.setObjectName("t_paths")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.t_paths)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.l_paths = QtWidgets.QVBoxLayout()
        self.l_paths.setObjectName("l_paths")
        self.verticalLayout_12.addLayout(self.l_paths)
        self.tabWidget.addTab(self.t_paths, "")
        self.t_map = QtWidgets.QWidget()
        self.t_map.setObjectName("t_map")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.t_map)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.l_map = QtWidgets.QVBoxLayout()
        self.l_map.setObjectName("l_map")
        self.verticalLayout_11.addLayout(self.l_map)
        self.tabWidget.addTab(self.t_map, "")
        self.t_map_in_paths = QtWidgets.QWidget()
        self.t_map_in_paths.setObjectName("t_map_in_paths")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.t_map_in_paths)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.l_map_in_paths = QtWidgets.QVBoxLayout()
        self.l_map_in_paths.setObjectName("l_map_in_paths")
        self.verticalLayout_10.addLayout(self.l_map_in_paths)
        self.tabWidget.addTab(self.t_map_in_paths, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1211, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.d_status = QtWidgets.QStatusBar(MainWindow)
        self.d_status.setObjectName("d_status")
        MainWindow.setStatusBar(self.d_status)
        self.a_load = QtWidgets.QAction(MainWindow)
        self.a_load.setObjectName("a_load")
        self.actionAdvanced_Settings = QtWidgets.QAction(MainWindow)
        self.actionAdvanced_Settings.setObjectName("actionAdvanced_Settings")
        self.menubar.addAction(self.menuFile.menuAction())
        self.label_7.setBuddy(self.f_drift_density)
        self.label_8.setBuddy(self.f_drift_radius)
        self.label_9.setBuddy(self.f_dataset_interpolation_type)

        self.retranslateUi(MainWindow)
        self.t_tabs.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.f_auto_slope.clicked['bool'].connect(self.f_slope.setDisabled)
        self.f_step_auto.clicked['bool'].connect(self.f_step_manual.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Log"))
        self.b_undo.setText(_translate("MainWindow", "Undo"))
        self.groupBox.setTitle(_translate("MainWindow", "Slope Correction"))
        self.label_4.setText(_translate("MainWindow", "Hsat:"))
        self.f_auto_slope.setText(_translate("MainWindow", "Auto"))
        self.f_slope.setPlaceholderText(_translate("MainWindow", "Enter slope manually..."))
        self.groupBox_9.setTitle(_translate("MainWindow", "Import"))
        self.f_drift.setText(_translate("MainWindow", "Drift Correction"))
        self.label_7.setText(_translate("MainWindow", "Density:"))
        self.label_8.setText(_translate("MainWindow", "Kernel size:"))
        self.label_9.setText(_translate("MainWindow", "Interpolation:"))
        self.label_10.setText(_translate("MainWindow", "Fieldstep:"))
        self.f_step_auto.setText(_translate("MainWindow", "Auto"))
        self.f_step_manual.setPlaceholderText(_translate("MainWindow", "Enter step manually..."))
        self.f_dataset_interpolation_type.setItemText(0, _translate("MainWindow", "cubic"))
        self.f_dataset_interpolation_type.setItemText(1, _translate("MainWindow", "linear"))
        self.f_dataset_interpolation_type.setItemText(2, _translate("MainWindow", "nearest"))
        self.groupBox_2.setTitle(_translate("MainWindow", "FORC Distribution"))
        self.label_2.setText(_translate("MainWindow", "Extension:"))
        self.f_extension_type.setItemText(0, _translate("MainWindow", "flat"))
        self.f_extension_type.setItemText(1, _translate("MainWindow", "slope"))
        self.f_extension_type.setItemText(2, _translate("MainWindow", "truncate"))
        self.label_6.setText(_translate("MainWindow", "Fit points:"))
        self.label_5.setText(_translate("MainWindow", "Smoothing Factor:"))
        self.t_tabs.setTabText(self.t_tabs.indexOf(self.tab), _translate("MainWindow", "Settings"))
        self.groupBox_11.setTitle(_translate("MainWindow", "2D Plot Options"))
        self.label_14.setText(_translate("MainWindow", "Mask:"))
        self.f_2d_mask.setItemText(0, _translate("MainWindow", "H<Hr"))
        self.f_2d_mask.setItemText(1, _translate("MainWindow", "none"))
        self.label_16.setText(_translate("MainWindow", "Colormap:"))
        self.f_2d_cmap.setText(_translate("MainWindow", "RdBu_r"))
        self.label_11.setText(_translate("MainWindow", "Coordinates:"))
        self.f_hhr.setText(_translate("MainWindow", "(H, Hr)"))
        self.f_hchb.setText(_translate("MainWindow", "(Hc, Hb)"))
        self.groupBox_10.setTitle(_translate("MainWindow", "FORC Paths"))
        self.label_15.setText(_translate("MainWindow", "Mask:"))
        self.f_paths_mask.setItemText(0, _translate("MainWindow", "H<Hr"))
        self.f_paths_mask.setItemText(1, _translate("MainWindow", "none"))
        self.f_paths_mask.setItemText(2, _translate("MainWindow", "outline"))
        self.label_13.setText(_translate("MainWindow", "Colormap:"))
        self.f_paths_cmap.setItemText(0, _translate("MainWindow", "viridis"))
        self.label_12.setText(_translate("MainWindow", "Points:"))
        self.f_paths_points.setItemText(0, _translate("MainWindow", "none"))
        self.f_paths_points.setItemText(1, _translate("MainWindow", "reversal"))
        self.f_paths_points.setItemText(2, _translate("MainWindow", "all"))
        self.t_tabs.setTabText(self.t_tabs.indexOf(self.tab_2), _translate("MainWindow", "Plotting"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Export"))
        self.b_export_vtk.setText(_translate("MainWindow", "VTK"))
        self.b_export_csv.setText(_translate("MainWindow", "CSV"))
        self.b_export_pmc.setText(_translate("MainWindow", "PMC Format"))
        self.t_tabs.setTabText(self.t_tabs.indexOf(self.tab_3), _translate("MainWindow", "Output"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Processing"))
        self.b_import.setText(_translate("MainWindow", "Import Data"))
        self.b_slope.setText(_translate("MainWindow", "Slope Correction"))
        self.b_normalize.setText(_translate("MainWindow", "Normalize Moment"))
        self.b_gauss.setText(_translate("MainWindow", "Gaussian Filter"))
        self.b_forc.setText(_translate("MainWindow", "FORC Distribution"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Plotting"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Heat Map"))
        self.b_heat_moment.setText(_translate("MainWindow", "M"))
        self.b_heat_rho.setText(_translate("MainWindow", "ρ"))
        self.b_heat_rho_uncertainty.setText(_translate("MainWindow", "Δρ"))
        self.b_heat_temperature.setText(_translate("MainWindow", "T"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Levels"))
        self.b_level_moment.setText(_translate("MainWindow", "M"))
        self.b_level_rho.setText(_translate("MainWindow", "ρ"))
        self.b_level_rho_uncertainty.setText(_translate("MainWindow", "Δρ"))
        self.b_level_temperature.setText(_translate("MainWindow", "T"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Contours"))
        self.b_contour_moment.setText(_translate("MainWindow", "M"))
        self.b_contour_rho.setText(_translate("MainWindow", "ρ"))
        self.b_contour_rho_uncertainty.setText(_translate("MainWindow", "Δρ"))
        self.b_contour_temperature.setText(_translate("MainWindow", "T"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Map into Curves"))
        self.b_map_curves_moment.setText(_translate("MainWindow", "M"))
        self.b_map_curves_rho.setText(_translate("MainWindow", "ρ"))
        self.b_map_curves_rho_uncertainty.setText(_translate("MainWindow", "Δρ"))
        self.b_map_curves_temperature.setText(_translate("MainWindow", "T"))
        self.b_hc_axis.setText(_translate("MainWindow", "Hc Axis"))
        self.b_paths.setText(_translate("MainWindow", "Paths"))
        self.b_h_axis.setText(_translate("MainWindow", "H Axis"))
        self.b_data_points.setText(_translate("MainWindow", "Points"))
        self.b_hb_axis.setText(_translate("MainWindow", "Hb Axis"))
        self.b_hr_axis.setText(_translate("MainWindow", "Hr Axis"))
        self.b_major_loop.setText(_translate("MainWindow", "Major Loop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.t_paths), _translate("MainWindow", "Paths"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.t_map), _translate("MainWindow", "Map"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.t_map_in_paths), _translate("MainWindow", "Map In Paths"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.a_load.setText(_translate("MainWindow", "Load..."))
        self.actionAdvanced_Settings.setText(_translate("MainWindow", "Advanced Settings"))


